"""Add email_verified field to users

Revision ID: 43933116c651
Revises: 
Create Date: 2025-11-08 12:36:34.936508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43933116c651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value for existing rows
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###

