"""Add friend_invitations table

Revision ID: 74f7ca8b76b3
Revises: 43933116c651
Create Date: 2025-11-08 15:05:55.797283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '74f7ca8b76b3'
down_revision = '43933116c651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if table already exists
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    # Only create table if it doesn't exist
    if 'friend_invitations' not in tables:
        op.create_table('friend_invitations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('inviter_id', sa.UUID(), nullable=False),
        sa.Column('invitee_email', sa.String(), nullable=False),
        sa.Column('invitation_token', sa.String(), nullable=False),
        sa.Column('accepted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_friend_invitations_id'), 'friend_invitations', ['id'], unique=False)
        op.create_index(op.f('ix_friend_invitations_invitation_token'), 'friend_invitations', ['invitation_token'], unique=True)
        op.create_index(op.f('ix_friend_invitations_invitee_email'), 'friend_invitations', ['invitee_email'], unique=False)
        op.create_index(op.f('ix_friend_invitations_inviter_id'), 'friend_invitations', ['inviter_id'], unique=False)
        print("✅ Created friend_invitations table")
    else:
        print("⏭️  Table friend_invitations already exists, skipping creation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_invitations_inviter_id'), table_name='friend_invitations')
    op.drop_index(op.f('ix_friend_invitations_invitee_email'), table_name='friend_invitations')
    op.drop_index(op.f('ix_friend_invitations_invitation_token'), table_name='friend_invitations')
    op.drop_index(op.f('ix_friend_invitations_id'), table_name='friend_invitations')
    op.drop_table('friend_invitations')
    # ### end Alembic commands ###

